Repository hmcts/ccpay-bubble, pull requests merged in 2019-09, with the labels that each got.

#191 Update PayhubService.js
  express/services/PayhubService.js
Labels: ns:ccpay-bubble-frontend-pr-191

#194 Update PayhubService.js
  express/services/PayhubService.js
Labels: ns:ccpay-bubble-frontend-pr-194

#190 add bulkscan component to helm charts
  charts/ccpay-bubble-frontend/values.yaml
Labels: ns:ccpay-bubble-frontend-pr-190

#199 updating package json version changes
  package.json
  yarn.lock
Labels: ns:ccpay-bubble-frontend-pr-199

#206 Pay 2183
  projects/fee-register-search/src/lib/components/fee-search/fee-search.component.html
  src/app/components/ccd-search/ccd-search.component.html
  src/app/components/ccd-search/ccd-search.component.scss
  src/app/components/fee-search/fee-search.component.html
  src/app/shared/components/navigation/navigation.component.html
  yarn.lock
Labels: ns:ccpay-bubble-frontend-pr-206

#178 PAY-1904
  src/app/components/fee-details/fee-details.component.html
  src/app/components/fee-details/fee-details.component.spec.ts
  src/app/components/fee-details/fee-details.component.ts
  src/app/components/fee-search/fee-search.component.spec.ts
  src/app/components/fee-search/fee-search.component.ts
  src/app/services/httpclient/paybubble.http.client.spec.ts
Labels: ns:ccpay-bubble-frontend-pr-178

#209 Fix AAT build pipeline
  infrastructure/main.tf
Labels: ns:ccpay-bubble-frontend-pr-209

#208 Updating Idam URL in production
  infrastructure/prod.tfvars
Labels: ns:ccpay-bubble-frontend-pr-208

#212 [[KN]]- Updated CCD URL TO Prod
  infrastructure/aat.tfvars
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:ccpay-bubble-frontend-pr-212
