Repository hmcts/ccpay-bubble, pull requests merged in 2020-10, with the labels that each got.

#354 Merge all paybubble enhancement changes
  src/app/components/ccd-search/ccd-search.component.html
  src/app/components/ccd-search/ccd-search.component.spec.ts
  src/app/components/ccd-search/ccd-search.component.ts
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-354

#361 PAY-3688 DATA loss new line issue
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-361

#358 Pay 3147 strategic fix
  express/app.js
  express/mvc/controller/PayhubController.js
  express/services/PayhubService.js
  package.json
  src/app/components/ccd-search/ccd-search.component.spec.ts
  src/app/components/ccd-search/ccd-search.component.ts
  src/app/components/fee-search/fee-search.component.spec.ts
  src/app/components/fee-search/fee-search.component.ts
  src/app/components/payment-history/payment-history.component.html
  src/app/components/payment-history/payment-history.component.ts
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-358

#370 Azure rm upgrade changes
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-370

#374 AZURE RM version changes
  src/app/components/ccd-search/ccd-search.component.spec.ts
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-374

#375 Pay 3472 fr telephoney
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-375

#377 Pay 3340 live
  package.json
  src/app/components/ccd-search/ccd-search.component.html
  src/app/components/fee-details/fee-details.component.html
  src/app/components/fee-search/fee-search.component.html
  src/app/shared/components/phase-banner/phase-banner.component.html
  src/app/shared/components/phase-banner/phase-banner.component.spec.ts
  src/app/shared/components/phase-banner/phase-banner.component.ts
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-377

#373 Pay 3752 transferred reason
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-373

#379 functional tests added along with nightly build
  Jenkinsfile_nightly
  acceptance-tests/test/end-to-end/pages/steps_file.js
  acceptance-tests/test/end-to-end/tests/CCPB_SearchCaseWithCCD_test.js
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-379

#380 Modified package.json
  package.json
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-380
