Repository hmcts/ccpay-bubble, pull requests merged in 2020-12, with the labels that each got.

#378 PAY-3764 - Apportionment live INC changes
  src/app/components/ccd-search/ccd-search.component.html
  src/app/components/ccd-search/ccd-search.component.scss
  src/app/components/ccd-search/ccd-search.component.spec.ts
  src/app/components/ccd-search/ccd-search.component.ts
  src/app/components/fee-details/fee-details.component.spec.ts
  src/app/services/payment-group/payment-group.service.ts
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-378

#376 Pay 3732 siteid dropdown
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-376

#389 Exception Changes
  acceptance-tests/test/end-to-end/pages/steps_file.js
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-389
