Repository hmcts/ccpay-bubble, pull requests merged in 2021-08, with the labels that each got.

#507 vulnarability fix
  src/app/shared/components/phase-banner/phase-banner.component.ts
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-507

#510 unit test fix
  src/app/components/fee-details/fee-details.component.spec.ts
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-510

#516 Nightly dev
  package.json
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-516
