Repository hmcts/ccpay-bubble, pull requests merged in 2021-11, with the labels that each got.

#566 PAY-5233&4953 v3
  acceptance-tests/test/end-to-end/pages/confirm_association.js
  acceptance-tests/test/end-to-end/pages/reports.js
  acceptance-tests/test/end-to-end/tests/CCPB_BulkScanFunctionality_test.js
  package.json
  src/app/app.module.ts
  src/app/components/add-fee-detail/add-fee-detail.component.html
  src/app/components/add-fee-detail/add-fee-detail.component.scss
  src/app/components/add-fee-detail/add-fee-detail.component.spec.ts
  src/app/components/add-fee-detail/add-fee-detail.component.ts
  src/app/routes/app-routing.module.ts
  src/app/shared/components/service-failure/service-failure.component.html
  src/app/shared/components/service-failure/service-failure.component.ts
  src/app/shared/components/service-failure/service.failure.component.spec.ts
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-566

#572 PAY-5330
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-572

#575 Fixed CVE issues
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-575
