Repository hmcts/ccpay-bubble, pull requests merged in 2021-04, with the labels that each got.

#455 Mutation report fix
  Jenkinsfile_nightly
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-455

#454 TA-490 Adding last 3 pa11y pages
  Jenkinsfile_nightly
  scripts/pa11y.js
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-454

#460 Changed fees desc and code due to fees data migration changes in func…
  acceptance-tests/test/end-to-end/pages/paybubble_static_data.js
  acceptance-tests/test/end-to-end/pages/steps_file.js
  acceptance-tests/test/end-to-end/tests/CCPB_BulkScanFunctionality_test.js
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-460

#462 cvefixes
  package.json
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-462
