Repository hmcts/ccpay-bubble, pull requests merged in 2021-02, with the labels that each got.

#402 Bulkscanfunctionalitieswithtags
  Jenkinsfile_nightly
  acceptance-tests/codecept.conf.js
  acceptance-tests/test/end-to-end/helpers/misc.js
  acceptance-tests/test/end-to-end/helpers/number_utils.js
  acceptance-tests/test/end-to-end/helpers/string_utils.js
  acceptance-tests/test/end-to-end/helpers/utils.js
  acceptance-tests/test/end-to-end/pages/add_fees.js
  acceptance-tests/test/end-to-end/pages/case_search.js
  acceptance-tests/test/end-to-end/pages/case_transactions.js
  acceptance-tests/test/end-to-end/pages/case_transferred.js
  acceptance-tests/test/end-to-end/pages/case_unidentified.js
  acceptance-tests/test/end-to-end/pages/confirm_association.js
  acceptance-tests/test/end-to-end/pages/fees_summary.js
  acceptance-tests/test/end-to-end/pages/paybubble_static_data.js
  acceptance-tests/test/end-to-end/pages/payment_history.js
  acceptance-tests/test/end-to-end/pages/remission.js
  acceptance-tests/test/end-to-end/pages/reports.js
  acceptance-tests/test/end-to-end/pages/steps_file.js
  acceptance-tests/test/end-to-end/tests/CCPBAcceptanceTestConstants.js
  acceptance-tests/test/end-to-end/tests/CCPB_BulkScanFunctionality_test.js
  acceptance-tests/test/end-to-end/tests/CCPB_SearchCaseWithCCD_test.js
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-402

#416 Nightly functional tests timeout increased to 90mins
  Jenkinsfile_nightly
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-416

#418 Pbnightlybuildfix
  acceptance-tests/test/end-to-end/helpers/misc.js
  acceptance-tests/test/end-to-end/pages/case_search.js
  acceptance-tests/test/end-to-end/pages/steps_file.js
  acceptance-tests/test/end-to-end/tests/CCPB_SearchCaseWithCCD_test.js
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-418

#425 Internal credential exposure fix - 2.0
  charts/ccpay-bubble-frontend/Chart.yaml
  charts/ccpay-bubble-frontend/requirements.yaml
  express/mvc/controller/PayhubController.js
  server.js
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-425

#387 PAY-3521-TransactionId-display
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-387
