Repository hmcts/ccpay-bubble, pull requests merged in 2022-07, with the labels that each got.

#673 4xx-Issue fixes
  charts/ccpay-bubble-frontend/Chart.yaml
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-673

#671 Cookie banner changes
  angular.json
  package.json
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/cookie-banner/cookie-banner.component.html
  src/app/components/cookie-banner/cookie-banner.component.scss
  src/app/components/cookie-banner/cookie-banner.component.spec.ts
  src/app/components/cookie-banner/cookie-banner.component.ts
  src/app/components/cookie-details/cookie-details.component.html
  src/app/components/cookie-details/cookie-details.component.scss
  src/app/components/cookie-details/cookie-details.component.spec.ts
  src/app/components/cookie-details/cookie-details.component.ts
  src/app/components/cookie-policy/cookie-policy.component.html
  src/app/components/cookie-policy/cookie-policy.component.scss
  src/app/components/cookie-policy/cookie-policy.component.spec.ts
  src/app/components/cookie-policy/cookie-policy.component.ts
  src/app/components/cookie-table/cookie-table.component.html
  src/app/components/cookie-table/cookie-table.component.scss
  src/app/components/cookie-table/cookie-table.component.spec.ts
  src/app/components/cookie-table/cookie-table.component.ts
  src/app/routes/app-routing.module.ts
  src/assets/js/gtm.js
  src/index.html
  src/window.ts
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-671

#681 Update README.md
  README.md
  src/app/components/cookie-details/cookie-details.component.html
  src/app/components/cookie-details/cookie-details.component.ts
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-681
