Repository hmcts/ccpay-bubble, pull requests merged in 2022-06, with the labels that each got.

#660 Update README.md
  README.md
  package.json
  yarn-audit-known-issues
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-660

#670 PAY-5512 - Disable cross browser test from nightly dev
  Jenkinsfile_nightly
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-670

#672 update cross browser tests config
  Jenkinsfile_nightly
  acceptance-tests/saucelabs.conf.js
  acceptance-tests/test/end-to-end/tests/CCPB_BulkScanFunctionality_test.js
  acceptance-tests/test/end-to-end/tests/CCPB_SearchCaseWithCCD_test.js
  package.json
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-672
