Repository hmcts/ccpay-bubble, pull requests merged in 2022-08, with the labels that each got.

#682 Merge confilct changes
  src/app/app.component.html
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-682

#678 add Pa11y Accessibility tests
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  acceptance-tests/codecept.conf.js
  acceptance-tests/test/end-to-end/accessibility-reporter/Report.html
  acceptance-tests/test/end-to-end/accessibility-reporter/customReporter.js
  acceptance-tests/test/end-to-end/accessibility-reporter/resources/angular.min.js
  acceptance-tests/test/end-to-end/accessibility-reporter/resources/css/all.css
  acceptance-tests/test/end-to-end/accessibility-reporter/resources/webfonts/fa-solid-900.woff2
  acceptance-tests/test/end-to-end/helpers/AccessibilityReportingHelper.js
  acceptance-tests/test/end-to-end/helpers/PuppeteerHelper.js
  acceptance-tests/test/end-to-end/helpers/accessibility/runner.js
  acceptance-tests/test/end-to-end/pages/steps_file.js
  acceptance-tests/test/end-to-end/tests/CCPB_BulkScanFunctionality_test.js
  acceptance-tests/test/end-to-end/tests/CCPB_SearchCaseWithCCD_test.js
  acceptance-tests/test/end-to-end/tests/config/CCPBConfig.js
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-678

#545 web component changes to remove 8X8 code
  .gitignore
  package.json
  src/app/components/ccd-search/ccd-search.component.spec.ts
  src/app/components/ccd-search/ccd-search.component.ts
  src/app/components/payment-history/payment-history.component.html
  src/app/components/payment-history/payment-history.component.ts
  src/test/java/.gitignore
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-545

#684 enabled cookie banner
  src/app/app.component.html
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-684

#675 PAY-5617 payment failure changes
  README.md
  charts/ccpay-bubble-frontend/Chart.yaml
  express/app.js
  express/mvc/controller/PayhubController.js
  express/services/PayhubService.js
  package.json
  src/app/components/ccd-search/ccd-search.component.ts
  src/app/components/fee-search/fee-search.component.spec.ts
  src/app/components/fee-search/fee-search.component.ts
  src/app/components/payment-history/payment-history.component.html
  src/app/components/payment-history/payment-history.component.ts
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-675
