Repository hmcts/ccpay-bubble, pull requests merged in 2023-07, with the labels that each got.

#791 SNI-3692: Referencing web component version 5.2.9
  acceptance-tests/test/end-to-end/pages/case_transactions.js
  acceptance-tests/test/end-to-end/pages/confirm_association.js
  acceptance-tests/test/end-to-end/pages/fees_summary.js
  acceptance-tests/test/end-to-end/tests/CCPB_BulkScanFunctionality_test.js
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-791

#796 PAY-6259: Update timeout.
  Jenkinsfile_CNP
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-796

#799 PAY-6406: Update to resolve CVE
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-799

#798 update refunds and crossbrowser tests config
  acceptance-tests/test/end-to-end/tests/CCPB_BulkScanFunctionality_test.js
  acceptance-tests/test/end-to-end/tests/RefundsV2LocalTests.js
  acceptance-tests/test/end-to-end/tests/Refunds_V2_test.js
  yarn-audit-known-issues
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-798
