Repository hmcts/ccpay-bubble, pull requests merged in 2023-10, with the labels that each got.

#797 PAY-6374-update version to 5.2.12
  acceptance-tests/test/end-to-end/tests/Refunds_V2_test.js
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-797, enable_keep_helm

#820 PAY-6611: Node 18 Upgrade Helm
  charts/ccpay-bubble-frontend/Chart.yaml
  charts/ccpay-bubble-frontend/values.yaml
  yarn-audit-known-issues
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-820

#822 PAY-6637: Pipeline failures 30th Oct 2023
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-822
