Repository hmcts/ccpay-bubble, pull requests merged in 2023-01, with the labels that each got.

#731 cve fix
  yarn-audit-known-issues
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-731

#732 cve fix
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-732

#734 PaymentStatusUpdateTests_Fix
  .eslintignore
  acceptance-tests/test/end-to-end/helpers/string_utils.js
  acceptance-tests/test/end-to-end/helpers/utils.js
  acceptance-tests/test/end-to-end/pages/case_transactions.js
  acceptance-tests/test/end-to-end/pages/failure_event_details.js
  acceptance-tests/test/end-to-end/tests/Payment_Failure_BounceBack_test.js
  yarn-audit-known-issues
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-734

#735 cve fix
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-735

#720 Pay 5682
  angular.json
  karma.conf.js
  package.json
  projects/fee-register-search/package.json
  projects/fee-register-search/src/lib/components/fee-list/fee-list.component.scss
  projects/fee-register-search/src/lib/fee-register-search.component.spec.ts
  projects/fee-register-search/src/lib/mocks/mock-fees.ts
  projects/fee-register-search/tsconfig.lib.json
  projects/fee-register-search/tsconfig.lib.prod.json
  projects/view-payment/package.json
  projects/view-payment/src/lib/view-payment.component.spec.ts
  projects/view-payment/src/lib/view-payment.service.spec.ts
  projects/view-payment/tsconfig.lib.json
  projects/view-payment/tsconfig.lib.prod.json
  src/.browserslistrc
  src/app/components/confirmation/confirmation.component.spec.ts
  src/app/components/confirmation/route-guards/confirmation-guard.service.spec.ts
  src/app/components/cookie-banner/cookie-banner.component.spec.ts
  src/app/components/cookie-details/cookie-details.component.spec.ts
  src/app/components/cookie-policy/cookie-policy.component.spec.ts
  src/app/components/cookie-table/cookie-table.component.spec.ts
  src/app/components/fee-details/fee-details.component.spec.ts
  src/app/components/fee-search/fee-search.component.spec.ts
  src/app/components/payment-history/payment-history.component.spec.ts
  src/app/components/review-fee-detail/route-guards/review-fee-detail.service.spec.ts
  src/app/components/view-payment/view-payment.component.spec.ts
  src/app/routes/app-routing.module.ts
  src/app/services/payment-group/payment-group.service.spec.ts
  src/app/services/payment-group/payment-group.service.ts
  src/app/shared/components/fee-list-table/fee-list-table.component.spec.ts
  src/app/shared/components/header/header.component.spec.ts
  src/app/shared/components/navigation/navigation.component.spec.ts
  src/app/shared/components/phase-banner/phase-banner.component.spec.ts
  src/app/shared/components/service-failure/service.failure.component.spec.ts
  src/tsconfig.app.json
  tsconfig.json
  tslint.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-720

#738 uncommenting Payment status update FE_FN tests
  acceptance-tests/test/end-to-end/helpers/misc.js
  acceptance-tests/test/end-to-end/pages/case_transactions.js
  acceptance-tests/test/end-to-end/tests/Payment_Failure_BounceBack_test.js
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-738

#742 cve fix and disable fortify scan
  Jenkinsfile_nightly
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-742

#741 updated deprecated after to afterAlways
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
  charts/ccpay-bubble-frontend/Chart.yaml
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-741

#744 Upgraded Terraform version to 1.3.7
  infrastructure/.terraform-version
Labels: ns:fees-pay, prd:ccpay, no-changes, rel:ccpay-bubble-frontend-pr-744
