Repository hmcts/ccpay-bubble, pull requests merged in 2023-06, with the labels that each got.

#784 Test Pay Bubble master build in PR
  README.md
  karma.conf.js
  package.json
  projects/fee-register-search/karma.conf.js
  projects/view-payment/karma.conf.js
  src/app/services/payment-group/payment-group.service.spec.ts
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-784

#792 Pay 5980 web componets
  acceptance-tests/test/end-to-end/tests/Refunds_V2_test.js
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-792

#793 PAY-6040: Add suppressions.
  yarn-audit-known-issues
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-793

#794 PAY-6040: Remove flakey refund tests
  acceptance-tests/test/end-to-end/tests/Refunds_V2_test.js
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-794
