Repository hmcts/ccpay-bubble, pull requests merged in 2024-05, with the labels that each got.

#875 Fix FTs as per new fee changes
  acceptance-tests/test/end-to-end/pages/add_fees.js
  acceptance-tests/test/end-to-end/pages/steps_file.js
  acceptance-tests/test/end-to-end/tests/CCPB_BulkScanFunctionality_test.js
  acceptance-tests/test/end-to-end/tests/Refund_Full_Payment_Option_Selection_Journey_test.js
  acceptance-tests/test/end-to-end/tests/Refund_Over_Payment_Option_Selection_Journey_test.js
  acceptance-tests/test/end-to-end/tests/Refund_Rejected_Journey_test.js
  acceptance-tests/test/end-to-end/tests/Refund_Retro_Remission_Journey_test.js
  acceptance-tests/test/end-to-end/tests/Refund_SentBackToCaseworker_Journey_test.js
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-875

#863 Feature/pay 6748 footer accessiblity and cookies
  .gitignore
  gulpfile.js
  package.json
  src/app/app.component.html
  src/app/app.constants.ts
  src/app/app.module.ts
  src/app/components/accessibility-statement/accessibility-statement.component.html
  src/app/components/accessibility-statement/accessibility-statement.component.scss
  src/app/components/accessibility-statement/accessibility-statement.component.spec.ts
  src/app/components/accessibility-statement/accessibility-statement.component.ts
  src/app/components/ccd-search/ccd-search.component.html
  src/app/components/cookie-banner/cookie-banner.component.spec.ts
  src/app/components/cookie-banner/cookie-banner.component.ts
  src/app/components/cookie-policy/cookie-policy.component.html
  src/app/components/cookie-policy/cookie-policy.component.spec.ts
  src/app/components/cookie-policy/cookie-policy.component.ts
  src/app/components/fee-details/fee-details.component.html
  src/app/components/review-fee-detail/review-fee-detail.component.html
  src/app/routes/app-routing.module.ts
  src/app/shared/components/footer/footer.component.html
  src/app/shared/components/footer/footer.component.scss
  src/app/shared/components/footer/footer.component.spec.ts
  src/app/shared/components/footer/footer.component.ts
  src/app/shared/components/footer/footer.model.ts
  src/app/shared/components/hmcts-global-footer/hmcts-global-footer.component.html
  src/app/shared/components/hmcts-global-footer/hmcts-global-footer.component.spec.ts
  src/app/shared/components/hmcts-global-footer/hmcts-global-footer.component.ts
  src/app/shared/components/navigation/navigation.component.html
  src/app/shared/components/phase-banner/phase-banner.component.html
  src/assets/images/govuk-crest-2x.png
  src/assets/images/govuk-crest.png
  src/assets/js/cookie-manager-1.0.0.min.js
  src/assets/js/cookie.js
  src/assets/stylesheets/app/_buttons.scss
  src/assets/stylesheets/app/_components.scss
  src/assets/stylesheets/app/_nav.scss
  src/assets/stylesheets/app/index.scss
  src/assets/stylesheets/main.css
  src/assets/stylesheets/main.scss
  src/index.html
  yarn-audit-known-issues
  yarn.lock
Labels: Do not merge, ns:fees-pay, prd:ccpay, enable_keep_helm, rel:ccpay-bubble-frontend-pr-863

#878 Critical CVE fix.
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-878

#882 PAY-7126: Pipeline fixes - week beginning 13 May 2024
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-882

#873 PAY-6926: Calculate the AMOUNT DUE and OVERPAYMENTS for Upfront and R…
  acceptance-tests/test/end-to-end/pages/add_fees.js
  acceptance-tests/test/end-to-end/pages/case_transactions.js
  acceptance-tests/test/end-to-end/pages/confirm_association.js
  acceptance-tests/test/end-to-end/pages/initiate_refunds.js
  acceptance-tests/test/end-to-end/pages/paybubble_static_data.js
  acceptance-tests/test/end-to-end/pages/refunds_list.js
  acceptance-tests/test/end-to-end/tests/CCPBAcceptanceTestConstants.js
  acceptance-tests/test/end-to-end/tests/CCPB_BulkScanFunctionality_test.js
  acceptance-tests/test/end-to-end/tests/Refund_Over_Payment_Option_Selection_Journey_test.js
  acceptance-tests/test/end-to-end/tests/Refund_Retro_Remission_Journey_test.js
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, keep-helm, enable_keep_helm, rel:ccpay-bubble-frontend-pr-873

#890 Cves Pug
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, keep-helm, enable_keep_helm, rel:ccpay-bubble-frontend-pr-890

#894 Pay 5560 add security scan
  Jenkinsfile_nightly
  audit.json
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-894

#874 PAY-7021 angular 17
  angular.json
  package.json
  projects/fee-register-search/src/test.ts
  projects/view-payment/src/test.ts
  src/polyfills.ts
  src/test.ts
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, keep-helm, enable_keep_helm, rel:ccpay-bubble-frontend-pr-874
