Repository hmcts/ccpay-bubble, pull requests merged in 2024-09, with the labels that each got.

#905 PAY-7200: Front end changes to Calculate the AMOUNT DUE and OVERPAYME…
  acceptance-tests/test/end-to-end/tests/Refund_Over_Payment_Option_Selection_Journey_test.js
  acceptance-tests/test/end-to-end/tests/Refund_Retro_Remission_Journey_test.js
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, enable_keep_helm, rel:ccpay-bubble-frontend-pr-905

#916 Cves
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-916

#918 PAY-7319 pipeline fixes
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-918

#920 PAY-7317: Remove uncessary health checks
  express/infrastructure/health-info.js
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-920

#921 PAY-7347 rerun know-issues for vulnerabilities
  yarn-audit-known-issues
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-921

#919 add and upodate FTs
  acceptance-tests/test/end-to-end/pages/initiate_refunds.js
  acceptance-tests/test/end-to-end/pages/paybubble_static_data.js
  acceptance-tests/test/end-to-end/tests/Refund_Retro_Remission_Journey_test.js
  acceptance-tests/test/end-to-end/tests/RefundsV2LocalTests.js
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-919

#915 PAY-7285
  acceptance-tests/test/end-to-end/pages/reports.js
  express/app.js
  express/mvc/controller/PayhubController.js
  express/services/PayhubService.js
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-915

#926 Pay 7365 new pass
  server.js
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-926

#927 PAY-7365: Pipeline fixes - week beginning 23nd October 2024
  audit.json
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-927

#928 PAY-7365: Pipeline fixes - week beginning 23nd October 2024
  acceptance-tests/test/end-to-end/tests/CCPB_BulkScanFunctionality_test.js
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-928
