Repository hmcts/ccpay-bubble, pull requests merged in 2024-06, with the labels that each got.

#888 Pay 7126
  sonar-project.properties
  src/app/app.component.html
  src/app/app.module.ts
  src/app/components/accessibility-statement/accessibility-statement.component.html
  src/app/components/accessibility-statement/accessibility-statement.component.scss
  src/app/components/accessibility-statement/accessibility-statement.component.spec.ts
  src/app/components/accessibility-statement/accessibility-statement.component.ts
  src/app/components/cookie-banner/cookie-banner.component.spec.ts
  src/app/components/cookie-banner/cookie-banner.component.ts
  src/app/components/cookie-policy/cookie-policy.component.html
  src/app/components/cookie-policy/cookie-policy.component.spec.ts
  src/app/components/cookie-policy/cookie-policy.component.ts
  src/app/routes/app-routing.module.ts
  src/app/shared/components/footer/footer.component.html
  src/app/shared/components/footer/footer.component.scss
  src/app/shared/components/footer/footer.component.spec.ts
  src/app/shared/components/footer/footer.component.ts
  src/app/shared/components/footer/footer.model.ts
  src/assets/images/govuk-crest-2x.png
  src/assets/images/govuk-crest.png
  src/assets/js/cookie-manager-1.0.0.min.js
  src/assets/js/cookie.js
  src/assets/stylesheets/main.scss
  src/index.html
Labels: ns:fees-pay, prd:ccpay, keep-helm, enable_keep_helm, rel:ccpay-bubble-frontend-pr-888

#896 PAY-7139 suppress verbose error messages
  README.md
  express/mvc/controller/BulkScanController.js
  express/mvc/controller/FeeController.js
  express/mvc/controller/NotificationController.js
  express/mvc/controller/PayhubController.js
  express/mvc/controller/RefundsController.js
  express/services/UtilService.js
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, enable_keep_helm, rel:ccpay-bubble-frontend-pr-896

#900 fix cves
  audit.json
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-900
