Repository hmcts/ccpay-bubble, pull requests merged in 2024-04, with the labels that each got.

#861 PAY-6948: ccpay-bubble functional test failure
  acceptance-tests/test/end-to-end/tests/Refund_Retro_Remission_Journey_test.js
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-861

#864 PBA Button fix web-component update,
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, enable_keep_helm, rel:ccpay-bubble-frontend-pr-864

#857 Pay 6927
  .gitignore
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, enable_keep_helm, rel:ccpay-bubble-frontend-pr-857

#867 PAY-6982 Node version update and auto close bot for PR
  .github/workflows/stale.yml
  charts/ccpay-bubble-frontend/Chart.yaml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-867

#869 PAY-7025 Pipeline fix
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-869

#868 PAY-6931 Add column for jurisdiction 2
  acceptance-tests/test/end-to-end/pages/add_fees.js
  projects/fee-register-search/src/lib/components/fee-list/fee-list.component.html
  projects/fee-register-search/src/lib/components/fee-list/fee-list.component.scss
  projects/fee-register-search/src/lib/components/fee-list/fee-list.component.spec.ts
  projects/fee-register-search/src/lib/components/fee-list/fee-list.component.ts
Labels: ns:fees-pay, prd:ccpay, enable_keep_helm, rel:ccpay-bubble-frontend-pr-868

#871 updates version for web-component hotfix
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, enable_keep_helm, rel:ccpay-bubble-frontend-pr-871
