Repository hmcts/ccpay-bubble, pull requests merged in 2024-03, with the labels that each got.

#851 PAY-5985: Restriction on Refund AMOUNT due to a Remission (Upfront an…
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-851

#859 PAY-6736: Welsh translation integration 2
  acceptance-tests/test/end-to-end/tests/CCPB_BulkScanFunctionality_test.js
  acceptance-tests/test/end-to-end/tests/Refund_Retro_Remission_Journey_test.js
  express/infrastructure/security.js
  package.json
  server.js
  src/app/app.module.ts
  start.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, enable_keep_helm, rel:ccpay-bubble-frontend-pr-859

#860 PAY-6806: Reverting change.
  acceptance-tests/test/end-to-end/pages/fees_summary.js
  acceptance-tests/test/end-to-end/pages/steps_file.js
  acceptance-tests/test/end-to-end/tests/CCPB_BulkScanFunctionality_test.js
  acceptance-tests/test/end-to-end/tests/CCPB_SearchCaseWithCCD_test.js
  express/infrastructure/security.js
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, enable_keep_helm, rel:ccpay-bubble-frontend-pr-860

#856 PAY-6830: Update to use excelJS
  .gitignore
  package.json
  src/app/components/ccd-search/ccd-search.component.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, enable_keep_helm, rel:ccpay-bubble-frontend-pr-856
