Repository hmcts/ccpay-bubble, pull requests merged in 2024-08, with the labels that each got.

#909 Pay 7231 pipeline fixes
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-909

#910 PAY-7120 updated yarn.lock file and web component version 6.2.5-beta01
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, keep-helm, rel:ccpay-bubble-frontend-pr-910

#914 PAY-7301: Fixing functional tests
  acceptance-tests/test/end-to-end/content/CCPBConfig.js
  acceptance-tests/test/end-to-end/pages/case_transactions.js
  acceptance-tests/test/end-to-end/tests/CCPBAcceptanceTestConstants.js
  acceptance-tests/test/end-to-end/tests/Refund_Over_Payment_Option_Selection_Journey_test.js
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-914

#912 PAY-7120 Rework for VUL-6113
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-912
