Repository hmcts/ccpay-bubble, pull requests merged in 2024-02, with the labels that each got.

#833 PAY-5918: Restriction on Refund CREATION due to a Remission (Upfront…
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-833

#848 PAY-6888
  yarn-audit-known-issues
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-848

#853 PAY-6911: Update to add short delay when changing dates.
  .gitignore
  acceptance-tests/test/end-to-end/pages/reports.js
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-853

#854 PAY-6911: Pipeline analysis and resolution 26 February 2023
  acceptance-tests/test/end-to-end/pages/reports.js
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-854
