Repository hmcts/ccpay-bubble, pull requests merged in 2024-01, with the labels that each got.

#832 Refactor and enable Refunds journey tests
  .eslintignore
  acceptance-tests/test/end-to-end/pages/initiate_refunds.js
  acceptance-tests/test/end-to-end/pages/payment_history.js
  acceptance-tests/test/end-to-end/tests/Refund_Full_Payment_Option_Selection_Journey_test.js
  acceptance-tests/test/end-to-end/tests/Refund_Over_Payment_Option_Selection_Journey_test.js
  acceptance-tests/test/end-to-end/tests/Refund_Partial_Journey_test.js
  acceptance-tests/test/end-to-end/tests/Refund_Rejected_Journey_test.js
  acceptance-tests/test/end-to-end/tests/Refund_Retro_Remission_Journey_test.js
  acceptance-tests/test/end-to-end/tests/Refund_SentBackToCaseworker_Journey_test.js
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-832

#837 add waits to fix FT failures
  acceptance-tests/test/end-to-end/tests/CCPB_BulkScanFunctionality_test.js
  acceptance-tests/test/end-to-end/tests/Refund_Partial_Journey_test.js
  acceptance-tests/test/end-to-end/tests/Refund_Retro_Remission_Journey_test.js
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-837

#838 PAY-6780: Update to show Payment Failure Event report
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, enable_keep_helm, rel:ccpay-bubble-frontend-pr-838

#839 PAY-6817: Update web-component fix Paybubble report initialisation
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, enable_keep_helm, rel:ccpay-bubble-frontend-pr-839
