Repository hmcts/ccpay-bubble, pull requests merged in 2025-05, with the labels that each got.

#958 PAY-7782: Pipeline fixes - week beginning 29nd April 2025
  Jenkinsfile_CNP
  package.json
  smoke-test/test/smoke-test.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, keep-helm, enable_keep_helm, rel:ccpay-bubble-frontend-pr-958

#961 PAY-7782: Update smoke test
  .nvmrc
  package.json
  smoke-test/smoke-codecept.conf.js
  smoke-test/test/smoke-test.js
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, enable_keep_helm, rel:ccpay-bubble-frontend-pr-961

#957 Updated package resolution for Axios to 1.8.4
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-bubble-frontend-pr-957

#954 CME-486
  package.json
  projects/fee-register-search/package.json
  projects/fee-register-search/src/lib/components/fee-filter/fee-filter.component.spec.ts
  projects/fee-register-search/src/lib/fee-register-search.component.spec.ts
  projects/fee-register-search/src/lib/services/fee-register-search/fee-register-search.service.spec.ts
  projects/view-payment/package.json
  projects/view-payment/src/lib/view-payment.component.spec.ts
  projects/view-payment/src/lib/view-payment.service.spec.ts
  src/app/app.module.ts
  src/app/components/confirmation/confirmation.component.spec.ts
  src/app/components/confirmation/route-guards/confirmation-guard.service.spec.ts
  src/app/components/review-fee-detail/route-guards/review-fee-detail.service.spec.ts
  src/app/components/view-payment/view-payment.component.spec.ts
  src/app/services/payment-group/payment-group.service.spec.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, enable_keep_helm, rel:ccpay-bubble-frontend-pr-954
