Repository hmcts/ccpay-bubble, pull requests merged in 2025-08, with the labels that each got.

#969 Pay 7881
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, keep-helm, enable_keep_helm, rel:ccpay-bubble-frontend-pr-969

#976 PAY-7730: Fees Selectable Day Before Change
  projects/fee-register-search/src/lib/pipes/filter-fees.pipe.ts
  projects/fee-register-search/src/lib/pipes/filter-fees.spec.ts
Labels: ns:fees-pay, prd:ccpay, enable_keep_helm, rel:ccpay-bubble-frontend-pr-976

#978 PAY-8004: Remission button grayed out against FEE0441 for 1728-5585-5…
  package.json
  yarn.lock
Labels: ns:fees-pay, prd:ccpay, keep-helm, enable_keep_helm, rel:ccpay-bubble-frontend-pr-978
